project_prefix   = "myproject"
rg_name          = "terraformproject-dev"
location         = "West US 2"
container_image  = "nginx:latest"
container_cpu    = "1"
container_memory = "2"
secret_ttl_hours = "48"